server:
  domain: 0.0.0.0
  port: 8080
jwt:
  keyStorePath: keystore.jceks
  password: cXHv1i/uP9ozQ/nA76cLvst5LBCuGYwQj2gH8xGno+Q=
  algorithm: ES512
  issuer: Cryptax
  expiresInMinutes: 30
  refreshExpiresInDays: 10
email:
  host: smtp.mail.yahoo.com
  port: 465
  from: webmaster.stock@yahoo.com
  username: webmaster.stock
  password: QB5LX65NOI3erVB04kMNEUgLWIDpkHjy3z//aAIzFy4=
http:
  maxIdleConnections: 50
  keepAliveDuration: 15
db:
  mode: cloud-datastore
  projectId: cryptax-212416
