server:
  domain: 0.0.0.0
  port: 8080
  allowOrigin: http://localhost:3000
jwt:
  keyStorePath: keystore.jceks
  password: cXHv1i/uP9ozQ/nA76cLvst5LBCuGYwQj2gH8xGno+Q=
  algorithm: HS512
  issuer: Cryptax
  expiresInMinutes: 30
  refreshExpiresInDays: 10
email:
  enabled: false
  url: https://us-central1-cryptax-backend-dev.cloudfunctions.net/
  function: sendgridEmail
  key: QcTncvSiPXDSGM89uGufBjZ4eNTTz6Cxqo2tjfUiJPbdMLELmXClanQVqfuU2Mx7CLnSVXXsuCnqdXtJ82Y3+yIfnwG8inW70jQLU5LC384=
  from: noreply@cryptax.app
  verifyUrl: http://localhost:3000/verify-user
http:
  maxIdleConnections: 5
  keepAliveDuration: 5
db:
  mode: in-memory
  projectId:
  credentials:
