server:
  domain: 0.0.0.0
  port: 8080
jwt:
  keyStorePath: keystore-it.jceks
  password: secret
  algorithm: ES512
  issuer: Cryptax
  expiresInMinutes: 30
  refreshExpiresInDays: 10
email:
  host: smtp.mail.yahoo.com
  port: 465
  from: webmaster.stock@yahoo.com
  username: webmaster.stock
  password: QB5LX65NOI3erVB04kMNEUgLWIDpkHjy3z//aAIzFy4=
http:
  maxIdleConnections: 5
  keepAliveDuration: 5
db:
  mode: in-memory
  url:
  name:
  username:
  password:
  socketFactory:
  socketFactoryArg:
  useSSL:
