#env:
#  - DOCKER_COMPOSE_VERSION=1.21.2

#before_install:
#  - sudo rm /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#  - sudo apt-get update
#  - sudo apt-get -y install docker-ce

#sudo: required

#services:
#  - docker

#script:
#  - docker-compose build

language: java
jdk:
  - oraclejdk10
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 61fe5130-3634-42c9-9e76-db79a3617daf
