version: '3.3'
services:
  backend:
    build: .
    container_name: backend
    hostname: cryptax
    ports:
      - '8080:8080'
    environment:
        - PROFILE=${PROFILE}
        - JASYPT_PASSWORD=${JASYPT_PASSWORD}
