version: '3.3'
services:
  backend:
    build:
      context: .
      args:
        PROFILE: ${PROFILE}
        JASYPT_PASSWORD: ${JASYPT_PASSWORD}
    container_name: backend
    hostname: cryptax
    ports:
      - '8080:8080'
