micronaut:
  application:
    name: cryptax
  server:
    cors:
      enabled: true

jackson:
  bean-introspection-module: true
  time-zone: UTC
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
  serialization-inclusion: NON_NULL
