steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg', 'JASYPT_PASSWORD=${_JASYPT_PASSWORD}',
         '--build-arg', 'PROFILE=${_PROFILE}',
         '--label', 'commit=$COMMIT_SHA',
         '-t', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME-latest',
         '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME-latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME-latest']
## Dirty trick to trigger a rolling update
#- name: 'gcr.io/cloud-builders/kubectl'
#  args: ['set', 'image', 'deployment/cryptax-backend', 'cryptax-backend=gcr.io/cryptax-backend-dev/backend:unknown']
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=$BRANCH_NAME-cluster'
#- name: 'gcr.io/cloud-builders/kubectl'
#  args: ['set', 'image', 'deployment/cryptax-backend', 'cryptax-backend=gcr.io/cryptax-backend-dev/backend:$BRANCH_NAME-latest']
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=$BRANCH_NAME-cluster'
