steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg', 'JASYPT_PASSWORD=${_JASYPT_PASSWORD}',
         '--build-arg', 'PROFILE=${_PROFILE}',
         '--label', 'commit=$COMMIT_SHA',
         '-t', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME-latest',
         '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME-latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'gcloud/app.yaml', '--image-url', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME-latest', '--version', '$BRANCH_NAME']
timeout: 1200s
