steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg', 'JASYPT_PASSWORD=${_JASYPT_PASSWORD}',
         '--build-arg', 'PROFILE=${_PROFILE}',
         '--label', 'commit=$COMMIT_SHA',
         '-t', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME-latest',
         '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME-latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml', '--image-url', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME-latest']
#- name: 'gcr.io/cloud-builders/kubectl'
#  args: ['apply', '-f', 'https://raw.githubusercontent.com/cryptax-org/cryptax-backend/$BRANCH_NAME/gcloud/deployment-$BRANCH_NAME.yaml', '--record']
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=$BRANCH_NAME-cluster'
