apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: cryptax-backend
spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: cryptax-backend
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: cryptax-backend
        spec:
            terminationGracePeriodSeconds: 30
            containers:
            - name: cryptax-backend
              image: gcr.io/cryptax-backend-dev/backend:develop-latest
              imagePullPolicy: Always
              ports:
              - containerPort: 8080
                protocol: TCP
            dnsPolicy: ClusterFirst
            restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: cryptax-backend
spec:
    selector:
        app: cryptax-backend
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: cryptax-ingress
    annotations:
        kubernetes.io/ingress.global-static-ip-name: dev-ip
        ingress.gcp.kubernetes.io/pre-shared-cert: "cryptax-star-certificate"
        kubernetes.io/ingress.allow-http: "false"
spec:
    backend:
        serviceName: cryptax-backend
        servicePort: 8080
